#!/bin/bash
IFS=' ' read -a words <<<"$@"
len=${#words[@]}
for (( i=0; i<$len; i++));
do
  echo  "${words[$i]}" | sed 's/\([^0-9]*\)\([0-9]*\)/\1:\2/' >> unsorted.txt
done
sort  -t: -k 1,1 -k 2,2n unsorted.txt  
  
